---
# GitHub username or organization and repo name
repo: markus1bauer/CI_vegetation_surveys

# Email address and user name that you want to associate with the automated deploys
# Generally you want these to be different from your user account so it is clear
# which commits are automated.
deploy_email: "markus1.bauer@tum.de"
deploy_username: "ci_markus"
---
